cuda: True
ngpu: 1
gpu_id: '4'
data_dir: /home/lih/RemoteRepo/VA_Project/Train     # Your dataset path

# test dataset
video_flist: '/home/lih/RemoteRepo/VA_Project/proj_demo/filelists/Video_Name_List.txt'
audio_flist: '/home/lih/RemoteRepo/VA_Project/proj_demo/filelists/Audio_Name_List.txt'

# part of training file-list to watch model's goodness of fitting training dataset
video_flist2: '/home/lih/RemoteRepo/VA_Project/proj_demo/filelists/Test_List_1.txt'
audio_flist2: '/home/lih/RemoteRepo/VA_Project/proj_demo/filelists/Test_List_1.txt'

workers: 4
batchSize: 40
checkpoint_folder: /home/lih/RemoteRepo/VA_Project/proj_demo/checkpoints

# initial model for evaluate.py
init_model: '/home/lih/RemoteRepo/VA_Project/proj_demo/checkpoints/VA_METRIC_state_epoch110.pth'

# initial model for UnionEvaluate.py
init_model_IBFC: '/home/lih/RemoteRepo/VA_Project/proj_demo/finalModels/IBFC_all.pth'
init_model_HFFC: '/home/lih/RemoteRepo/VA_Project/proj_demo/finalModels/HFFC_all.pth'
init_model_LSTM: '/home/lih/RemoteRepo/VA_Project/proj_demo/finalModels/LSTM_all.pth'

topk: 5
